name: build
on: push
jobs:
  build-10:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install build-essential perl cpanminus && cpanm . && perl Makefile.PL && make && make test
